### ISSUE TITLE
List all active orders for all Symbols

### ISSUE THREAD

**Issue by fahadysf** [sammchardy/python-kucoin#1]
Is there a way to get all active orders for any symbol? Doesn't seem obvious from the KuCoin API docs but the website itself has a page (Assets->Active Orders) which shows all orders. Am I missing something or is this not possible from the API?

**Comment by sammchardy** [comment]
Hi @fahadysf, the documentation
https://kucoinapidocs.docs.apiary.io/#reference/0/trading/list-active-orders
Shows a required symbol parameter, so it doesn't appear that you can get all active orders without looping through all symbol pairs.
Best option is to contact Kucoin directly and ask them to add the feature.

**Comment by crincones** [comment]
This is an old question, but it is possible, just leave the symbol blank, like this:

https://api.kucoin.com/v1/order/active-map?symbol=
