### ISSUE TITLE
Cancel_Order Fails on PIP 0.1.7

### ISSUE THREAD

**Issue by arenstar** [sammchardy/python-kucoin#10]
I recieve on a cancel_order

404
SYMBOL NOT FOUND

so reverted to 
0.1.0

**Comment by sammchardy** [comment]
Hi @arenstar can you update to v0.1.8 and try again.

If it's still failing can you give an example of how you're calling it.

**Comment by h3ct0rjs** [comment]
What symbol are you tryig to cancel

**Comment by Djusk8** [comment]
Have the same problem
Python 3.6
Python-kucoin v0.1.8
PIP 9.0.1 (I'll try v 0.1.0 later)

_ try1_
open_curr2_orders = client.get_active_orders(pair) _#pair = 'CAG-BTC'_
active_buy_order = open_curr2_orders['BUY'][0][5] _# active_buy_order = '5a658ecc36918d53e9ffa00f'_
client.cancel_order(active_buy_order, 'BUY')

**get error**
b'{"timestamp":1516607937246,"status":404,"error":"Not Found","message":"No message available","path":"/cancel-order"}'

_try2
open_curr2_orders = client.get_active_orders(pair) _#pair = 'CAG-BTC'_
active_buy_order = open_curr2_orders['BUY'][0][5] _# active_buy_order = '5a658ecc36918d53e9ffa00f'_
client.cancel_order(active_buy_order, 'BUY', **curr2**) _# curr2 = 'CAG'_

**get error**
KucoinAPIException ERROR: SYMBOL NOT FOUND

**Comment by sammchardy** [comment]
@Djusk8 I wasn't sure if the Not Found meant it couldn't find the order_id, if that's not the case then it means the symbol/pair is required and I need to enforce that. So many parameters when just an order_id should be all you need...

In your second example you just pass 'CAG' which is incorrect, it should be your `pair` value of 'CAG-BTC', can you try that.

**Comment by Djusk8** [comment]
Yes, 
I have 2 different errors:
 
try1 (w/o symbol/pair) - can't find order_id
try2 (w symbol pair) - can't find SYMBOL

**v3**

                        open_curr2_orders = client.get_active_orders(pair)  # {'SELL': [], 'BUY': [[1516605133000, 'BUY', 5.085e-05, 19.665683, 0.0, '5a658ecc36918d53e9ffa00f']]}
                        active_buy_order = open_curr2_orders['BUY'][0][5]  # '5a658ecc36918d53e9ffa00f'

                        # v1
                        #  client.cancel_order(active_buy_order, Client.SIDE_BUY)
                        # v2
                        #  client.cancel_order(active_buy_order, 'BUY', curr2)
                        # v3
                        client.cancel_order(active_buy_order, 'BUY', 'CAG-BTC')
**error**
KucoinAPIException ERROR: SYMBOL NOT FOUND

Actually I need to cancel order by it's Oid (v1), but when I get the error I tryed another variations of this command and found that its not working with any parameters.

**Comment by Djusk8** [comment]
Downgrade Python-kucoin to 0.1.7 and try

                        # v2
                        client.cancel_order(active_buy_order, pair, 'BUY')  # pair = "CAG-BTC"

And it's work well

**Comment by Djusk8** [comment]
I think i just found the problem! :)

Check your documentation at https://python-kucoin.readthedocs.io/en/latest/trading.html

description: 
cancel_order(order_id, **order_type, symbol=None**)

sample:
client.cancel_order(1, **'KCS-BTC', 'BUY'**)

Now it's working well, so I think issue can be closed

**Comment by h3ct0rjs** [comment]
I've tested that @Djusk8 , it works like a charm. 

Thank you

**Comment by sammchardy** [comment]
Closing because of new API version
