### ISSUE TITLE
Python doesnt recognize the module; ModuleNotFoundError

### ISSUE THREAD

**Issue by Zuenie** [sammchardy/python-kucoin#11]
I tried to follow the following steps: http://python-kucoin.readthedocs.io/en/latest/overview.html#initialise-the-client . My pip install looks fine. Yet when I run the code I get the error :  "ModuleNotFoundError: No module named 'kucoin.client'; 'kucoin' is not a package" 

I am no expert here, sorry if I ask a basic question, but could you help me out getting your module to be recognized by my python? 

Just checked out your binance module. That one does work! Makes me more confused.

**Comment by sammchardy** [comment]
Hi @Zuenie make sure your script isn't called kucoin.py or you have a directory named kucoin in the same path as your script. That's usually the issue.

**Comment by Zuenie** [comment]
Yes! Great. Thanks!
