### ISSUE TITLE
Cancel order stopped working: "Signature verification failed"

### ISSUE THREAD

**Issue by DerekMay** [sammchardy/python-kucoin#14]
*Windows 10
*Python 3.6.4
*I tried both python-kucoin v0.1.8 and v0.1.7

The API and the Client library is working for me in everything except any functions for cancelling orders which started failing last night (before that they were working fine as well). The error I keep getting is "Signature verification failed". Also today briefly, for a few hours, the cancel order functions started working again (!), without me changing anything in my code.

I tried using cancel_order or cancel_all_orders in many different ways, providing symbol or order type only, providing order_id etc. Nothing helped. 
Is this some issue on the Kucoin side or is there something we could do? Did Kucoin change anything?

It's strange how everything works except the cancel order calls...

**Comment by DerekMay** [comment]
Update: It again started working "by itself". 

It works for now, but I wonder what might be the cause of this possibly recurrent issue. 

Thanks in advance for any thoughts.

**Comment by DerekMay** [comment]
Quite unusual: 
This error was happening yesterday 3AM-11AM New York time.
Today exactly the same period, it started 3 AM and lasted until 11 AM, when it "miraculously" recovered.

Wondering if it has something to do with their IT support in China/HK.

**Comment by sammchardy** [comment]
Hi @DerekMay it does sound like a Kucoin infrastructure issue, it wouldn't be the first time they have had issues.

**Comment by DerekMay** [comment]
Thanks Sam,

Still not working for me tho...
Can anyone give me an example of a working cancel order?

**Comment by daviduartep** [comment]
I didn't have this issue when this bug was opened, but I started having this issue today.

kucoin.exceptions.KucoinAPIException: KucoinAPIException UNAUTH: Signature verification failed

Apparently only cancel order is being affected, I can get balances and historical data with no issues.

**Comment by DerekMay** [comment]
Hm, interesting.

**Comment by shovalyechiel** [comment]
when I asked the support they said you can cancel up to 1000 open trades per day Hong Kong time. maybe that's the issue. ? maybe you pass the limit ?

**Comment by DerekMay** [comment]
Cool, that would explain.

**Comment by Josi1337** [comment]
Could someone confirm that limit of 1000 cancels and did you guys get rid of it?

**Comment by DerekMay** [comment]
Sam, I was using your Big.one python package, it worked perfectly, but 10
days ago they made some changes to their API, so the package doesn’t work
anymore, not even for simple tasks like querying for account coin balances.

**Comment by sammchardy** [comment]
@DerekMay probably best asking over on python-bigone and not a closed python-kucoin ticket :)

You're in luck though, I had updated the bigone package for the new API. You're welcome.
