### ISSUE TITLE
No Timestamp

### ISSUE THREAD

**Issue by iero** [sammchardy/python-kucoin#15]
Dear all

After connection to the API, ```client.get_last_timestamp()``` return None

But other commands are working well.
Any other idea to get the server timestamp ?

**Comment by DerekMay** [comment]
Timestamp doesn't work for me either. It just stopped working. Also cancel_orders doesn't work for me, or it works off and on.

**Comment by sammchardy** [comment]
Hi @iero, this may not be completely clear or documented well. When performing requests to Kucoin the responses have a timestamp value in them, this is saved and is returned from `client.get_last_timestamp()`.

So best way to get it would be to call something small like `get_currencies` then follow up with `get_last_timestamp`

**Comment by iero** [comment]
Thanks for the explanation @sammchardy ! For information, I use your libraries in my project : [https://github.com/iero/Crypto](https://github.com/iero/Crypto)
