### ISSUE TITLE
how to show amount of withdrawal

### ISSUE THREAD

**Issue by emfls** [sammchardy/python-kucoin#17]
i used function of get_withdrawals('KCS')
But it was not show amount
Just i see these results.
{'total': 0, 'firstPage': True, 'lastPage': False, 'datas': [], 'currPageNo': 1, 'limit': 12, 'pageNos': 1}
I couldn't see amount.
I'll be waiting for the reply.
Finally, thank you for writing a good code.

**Comment by sammchardy** [comment]
Hi @emfls the documentation shows the response format if withdrawals have been made for that coin.

https://python-kucoin.readthedocs.io/en/latest/kucoin.html?highlight=withdr#kucoin.client.Client.get_withdrawals

The response above seems to indicate that no KCS withdrawals have been made from your account.

If that's not the case then I would contact Kucoin support.

**Comment by emfls** [comment]
Other coins were tested, but the results were the same. Did you try it yourself? If you've tried, can you show me what the results are?

**Comment by sammchardy** [comment]
Yes I have tested it on my account with BTC, I see a response similar to the one listed in the docs. I haven't made any KCS withdrawals so I can't test with that particular coin.

https://python-kucoin.readthedocs.io/en/latest/kucoin.html?highlight=withdr#kucoin.client.Client.get_withdrawals
