### ISSUE TITLE
client.get_order_details not working

### ISSUE THREAD

**Issue by MarcelBeining** [sammchardy/python-kucoin#23]
Unfortunately there are several issues with the  get_order_details method:
1) could not find the method in your documentation
2) From your code comments I extracted that the order id would be optional, but then the API responds "KucoinAPIException : Bad Request - Required String parameter 'orderOid' is not present" , so I guess it is not optional anymore
3) adding the order_id to the input arguments (symbol,order_type and order_id) does not give an error, but it also does not return anything (None). The order id and everything is correct and I tried it for different orders and symbols.

Thanks for having made that python wrapper!

**Comment by SnoozeTime** [comment]
Looks like a kucoin server issue. I tried to get order details without the python-kucoin package (just using requests), and here as well I got nothing for return value...

**Comment by MarcelBeining** [comment]
ok strange, I wrote kucoin. From my experience an answer cannot be expected within the next days...

**Comment by MarcelBeining** [comment]
That's what I received as answer from kucoin
"hi 

we don't provide api support ,could you  ask your friends for help. Thank you for your support.

best wishes

bessie"

Sounds like a joke.

**Comment by SnoozeTime** [comment]
Oh whoa. I'll abstain from trading with Kucoin API for some time anyway. 

Today, the cancel endpoint gave me a "System error" so it does not look reliable at all...

**Comment by sammchardy** [comment]
Closing because of new API version
