### ISSUE TITLE
Is there any way to check if a BUY/SELL order partially completed?

### ISSUE THREAD

**Issue by CallumHemsley** [sammchardy/python-kucoin#24]
We have get_active_orders() and get_dealt_orders() but if a order is partially filled, how do I know? Does it stay in active orders?

**Comment by sammchardy** [comment]
Hi @CallumHemsley yes it stays in active orders. And you have two values in the order details "dealtAmout" and "pendingAmount"

dealtAmount - is the amount that has been traded
pendingAmount - is the remainder left to be traded
