### ISSUE TITLE
get_recent_orders should actually be get_recent_trades

### ISSUE THREAD

**Issue by poks999** [sammchardy/python-kucoin#25]
get_recent_orders in the python-kucoin library points towards the endpoint

"GET https://api.kucoin.com/v1/open/deal-orders"

deal-orders is actually the trades. (The orders that became deals).

I did some testing and this is true. 

I bought 10 PRL and a qty 10 trade for 10PRL appeared. I put out an order for 10PRL at an outrageous price and nothing appeared

here is a screenshot comparing data i got from the endpoint to the recent trades on the kucoin site

https://i.imgur.com/K07gZxK.png

**Comment by sammchardy** [comment]
Yes it probably should be technically. I might add a second function that refers to it, so as not to break any existing scripts...

**Comment by rkarkicodesDAR** [comment]
Hi @sammchardy and @poks999,

I'm running into a issue. I'm trying to hit " GET https://api.kucoin.com/v1/deal-orders" endpoint but the request returns 404 with message " KucoinAPIException: KucoinAPIException UNAUTH: Login required".

I'm having trouble deciphering this error message. You guys happen to know how to resolve it?

**Comment by sammchardy** [comment]
Closing because of new API version
