### ISSUE TITLE
Can't withdraw using the API 

### ISSUE THREAD

**Issue by Jinqad** [sammchardy/python-kucoin#29]
```python
print(kucoin.create_withdrawal('BTC', amount, 'address'))
```
I just used this code will correct API keys and it raises the `kucoin.exceptions.KucoinAPIException: KucoinAPIException : b''`

**Comment by djohnson001** [comment]
I thought it was just me, but it sounds like this is on Kucoin's end. :)

https://news.kucoin.com/en/page/2/
"KuCoin API System and Security Question Login Maintenance
PUBLISHED 2018-04-19
Dear KuCoin Users,

We are performing an API system upgrade. For the time being, users won’t be able to withdraw through the API."
