### ISSUE TITLE
502 Bad Gateway response leads to KucoinAPIException, not KucoinRequestException

### ISSUE THREAD

**Issue by donglesquare** [sammchardy/python-kucoin#31]
> Traceback (most recent call last):
>   File "My file which calls get_all_balances",
>     result = ku_api.get_all_balances()
>   File "/usr/local/lib/python3.5/dist-packages/kucoin/client.py", line 975, in get_all_balances
>     return self._get('account/balance', True, data=data)
>   File "/usr/local/lib/python3.5/dist-packages/kucoin/client.py", line 177, in _get
>     return self._request('get', path, signed, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/kucoin/client.py", line 147, in _request
>     return self._handle_response(response)  
>   File "/usr/local/lib/python3.5/dist-packages/kucoin/client.py", line 156, in _handle_response                                     
>     raise KucoinAPIException(response)      
> kucoin.exceptions.KucoinAPIException: KucoinAPIException :
>  b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n'

It seems like 502 Bad Gateway response has to raise KucoinRequestException since it is not a valid json format. I wrote a code to print out error code and error message when KucoinAPIException has been raised.

The following is how I handle KucoinAPIException
```python
errormsg = 'KU API error with code: ' + str(e.status_code) + ' msg: ' + e.message
```
And at this time, it raises TypeError remarks that I cannot convert bytes to str implicitly.

**Comment by sammchardy** [comment]
Hi @donglesquare 

Instead of concatenating strings and other types of variables it can be best to use the str `format()` function, your example above would become

```
error msg = 'KU API error with code: {} msg: {}'.format(e.status_code, e.message)
```
