### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'sandbox'

### ISSUE THREAD

**Issue by inthecolors** [sammchardy/python-kucoin#44]
Hi there,
I was using older version and updated my environments due to use new version but I am getting this error for now. I couldn't recognize where is my fault. Also i created new sandbox api.

Error:
TypeError: __init__() got an unexpected keyword argument 'sandbox'

Python v=3.6.6

My codes:

api_key = "my_api_key"
api_secret = "my_api_secret"
api_passphrase = "my_api_passphrase"

from kucoin.client import Client
client = Client(api_key, api_secret, api_passphrase, sandbox=True)

currencies = client.get_currencies()
print(currencies)

**Comment by sammchardy** [comment]
Hi @inthecolors it seems like you may still be using the old client.

I would try clearing any installed libraries and reinstalling.

**Comment by inthecolors** [comment]
Thanks your reply, i fixed it.
