### ISSUE TITLE
cancel_withdrawal() giving a 'Method Not Allowed' error

### ISSUE THREAD

**Issue by kefirsutherman** [sammchardy/python-kucoin#5]
Have you been able to use the `cancel_withdrawal()` method successfully? When I run it it gives a me this error:

`kucoin.exceptions.KucoinAPIException: KucoinAPIException : Method Not Allowed`

Also which tx id should be passed as an argument? I'm currently trying to cancel a pending withdrawal and when I view it with `get_withdrawals()` there is a `outerWalletTxid` property and an `oid` property. Is `outerWalletTxid` the argument to pass to `cancel_withdrawal()`?

**Comment by adnbsr** [comment]
It is not related to this library. There should be something on KuCoin. I have same issue with `DRGN`

**Comment by jayarjo** [comment]
@kefirsutherman were you able to figure it out? Specifically the purpose of `outerWalletTxid ` and `oid` fields and what to pass into `cancel_withdrawal()`?

**Comment by sammchardy** [comment]
Closing because of new API version
