### ISSUE TITLE
Signature verification fail for "cancel order"

### ISSUE THREAD

**Issue by ntankovic** [sammchardy/python-kucoin#9]
Method `cancel_order` returns "Signature verification" error from Kucoin. The solution is to move `symbol` parameter from URI query to request body together with `orderOid` and `type`.

**Comment by sammchardy** [comment]
Hi @ntankovic can you upgrade to the latest version v0.1.8 and try again.

**Comment by sammchardy** [comment]
Going to close this, reopen if it's a problem again.

**Comment by ntankovic** [comment]
Thank you, it's OK now!
